#!/usr/bin/env python3

# ostree-push script for testing

import logging
import sys

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('tests/ostree-push')
logger.debug('sys.path=%s', ':'.join(sys.path))

from otpush import push  # noqa: E402
push.main()
