#!/usr/bin/env python3

# ostree-receive-0 script for testing

import logging
import sys

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('tests/ostree-receive-0')
logger.debug('sys.path=%s', ':'.join(sys.path))
logger.debug('sys.argv=%s', sys.argv)

from otpush import receive_legacy  # noqa: E402
sys.exit(receive_legacy.main())
