#!/usr/bin/python3

# ostree-push/ostree-receive - Push OSTree commits to a remote repo
# Copyright (C) 2023  Emanuele Aina <emanuele.aina@collabora.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os
import sys

if __name__ == '__main__':
    command = 'ostree-receive-1'
    if any(arg.startswith('--repo') for arg in sys.argv[1:]):
        command = 'ostree-receive-0'
    args = list(sys.argv)
    args[0] = command
    os.execvp(args[0], args)
