---
name: Tests

on: [push]

jobs:
  lint:
    name: Code style and lint checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            python3-pip

      - name: Install python dependencies
        run: |
          python3 -m pip install flake8

      - name: Run flake8
        run: |
          python3 -m flake8

  tests:
    strategy:
      # Let other configurations continue if one fails.
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu LTS
            image: ubuntu:latest
            setup: |
              apt-get update
              apt-get -y install \
                build-essential \
                flatpak \
                gir1.2-ostree-1.0 \
                libcairo2-dev \
                libgirepository1.0-dev \
                openssh-client \
                openssh-server \
                ostree \
                python3-dev \
                python3-pip \
                python3-setuptools \
                python3-wheel

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: System setup
        run: ${{ matrix.setup }}

      # sshd refuses to run if the hardcoded privilege separation
      # directory doesn't exist.
      - name: Create sshd privilege separation directory
        run: |
          mkdir -p /run/sshd

      - name: Install python dependencies
        run: |
          python3 -m pip install tox

      - name: Run tests
        run: |
          python3 -m tox
